name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  AZURE_LOCATION: 'eastus'
  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Azure CLI
        uses: azure/setup-azd@v1
        with:
          version: 'stable'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep templates
        run: |
          az bicep build --file ./infra/main.bicep
          
      - name: What-if deployment
        if: github.event_name == 'pull_request'
        run: |
          azd provision --preview --environment ${{ github.event.inputs.environment || 'development' }} --no-prompt
          
      - name: Post PR comment with changes
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = '${{ steps.what-if.outputs.changes }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `## Infrastructure Changes Preview\n\n\`\`\`\n${output}\n\`\`\``
            });

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    needs: validate
    if: github.event_name != 'pull_request'
    environment:
      name: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'development') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Azure Developer CLI
        uses: azure/setup-azd@v1
        with:
          version: 'stable'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure environment
        run: |
          azd env new ${{ github.event.inputs.environment || 'development' }} --location ${{ env.AZURE_LOCATION }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azd env set AZURE_SUBSCRIPTION_ID ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azd env set AZURE_LOCATION ${{ env.AZURE_LOCATION }}
          
      - name: Provision infrastructure
        run: |
          azd provision --environment ${{ github.event.inputs.environment || 'development' }} --no-prompt
          
      - name: Deploy application
        run: |
          azd deploy --environment ${{ github.event.inputs.environment || 'development' }} --no-prompt

      - name: Show deployment outputs
        run: |
          azd env get-values --environment ${{ github.event.inputs.environment || 'development' }}
