name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  AZURE_LOCATION: 'eastus'
  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Azure CLI
        uses: azure/setup-azd@v1
        with:
          version: 'stable'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep templates
        run: |
          az bicep build --file ./infra/main.bicep
          
      - name: What-if deployment
        if: github.event_name == 'pull_request'
        id: whatif
        run: |
          azd provision --preview --environment ${{ github.event.inputs.environment || 'development' }} --no-prompt
          
      - name: Post PR comment with changes
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = '${{ steps.whatif.outputs.changes }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `## Infrastructure Changes Preview\n\n\`\`\`\n${output}\n\`\`\``
            });

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    needs: validate
    if: github.event_name != 'pull_request'
    environment:
      name: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'development') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Azure Developer CLI
        uses: azure/setup-azd@v1
        with:
          version: 'stable'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure environment
        run: |
          azd env new ${{ github.event.inputs.environment || 'development' }} --location ${{ env.AZURE_LOCATION }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azd env set AZURE_SUBSCRIPTION_ID ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azd env set AZURE_LOCATION ${{ env.AZURE_LOCATION }}
          
      - name: Provision infrastructure
        run: |
          azd provision --environment ${{ github.event.inputs.environment || 'development' }} --no-prompt
          
      - name: Deploy application
        run: |
          azd deploy --environment ${{ github.event.inputs.environment || 'development' }} --no-prompt

      - name: Show deployment outputs
        run: |
          azd env get-values --environment ${{ github.event.inputs.environment || 'development' }}

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scanning
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./infra
          framework: bicep
          output_format: sarif
          output_file_path: results.sarif
          
      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  cost-estimation:
    runs-on: ubuntu-latest
    name: Cost Estimation
    needs: validate
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/setup-infracost@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate cost estimate
        run: |
          infracost breakdown --path ./infra \
            --format json \
            --out-file /tmp/infracost.json

      - name: Post cost estimate to PR
        run: |
          infracost comment github --path /tmp/infracost.json \
            --repo ${{ github.repository }} \
            --pull-request ${{ github.event.pull_request.number }} \
            --github-token ${{ github.token }}
